platform :ios, '13.0'
#use_frameworks!

target 'IdentiBreed' do

    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'

end
