platform :ios, '13.0'
#use_frameworks!

target 'IdentiBreedPerfected' do

    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Google-Mobile-Ads-SDK'

end
